In [1]:
# Libraries

import pandas as pd
import geopandas as gpd
import numpy as np
import math

import matplotlib
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from shapely.geometry import Polygon
from sklearn.cluster import DBSCAN

import operator

import random

In [2]:
data18 = pd.read_csv('../mexico/HH/2018_product_country.csv')

filter2 = pd.read_csv('../mexico/HH/filter2.csv')

In [3]:
# data18 = data18.head(10000)

In [4]:
data18["value_sqaure"] = data18['value'] ** 2

data18_grouped = (data18.groupby(['country_id', 'product_id']))

data18_grouped_square_sum = data18_grouped['value_sqaure', 'value'].agg('sum').reset_index()

data18_grouped_square_sum['concentration'] = data18_grouped_square_sum["value_sqaure"] / (data18_grouped_square_sum["value"])**2

In [5]:
data18_grouped_square_sum

        country_id  product_id  value_sqaure       value  concentration
0                4       10121  9.631690e+14  31122917.0       0.994356
1                4       10594  1.017799e+15  32677085.0       0.953181
2                4       10619  1.248359e+08     11173.0       1.000000
3                4       10632  2.310096e+08     15199.0       1.000000
4                4       20622  6.096754e+13  10262062.0       0.578934
5                4       30119  3.379715e+08     18384.0       1.000000
6                4       30384  1.570210e+14  13573930.0       0.852210
7                4       40210  9.905362e+14  85685584.0       0.134913
8                4       40291  9.302692e+14  44238500.0       0.475344
9                4       40310  1.883667e+14  13743703.0       0.997233
10               4       40390  4.021288e+09    131265.0       0.233382
11               4       40490  1.382348e+11    489294.0       0.577401
12               4       40610  2.834348e+12   3889723.0       0.187334
13               4       40711  1.929624e+11    655688.0       0.448826
14               4       40900  3.607880e+10    289111.0       0.431641
15               4       50400  8.296437e+09    123764.0       0.541630
16               4       60220  1.217297e+11    562625.0       0.384555
17               4       60311  2.234926e+09     47275.0       1.000000
18               4       60390  4.732064e+07      6879.0       1.000000
19               4       70200  3.467787e+14  26371388.0       0.498639
20               4       70320  3.665867e+11    719085.0       0.708951
21               4       70390  1.888151e+08     13741.0       1.000000
22               4       70410  2.120790e+08     14937.0       0.950541
23               4       70420  4.367432e+10    209903.0       0.991263
24               4       70511  2.051003e+09     45288.0       1.000000
25               4       70610  1.529261e+10    154871.0       0.637590
26               4       70810  2.750651e+14  16982675.0       0.953725
27               4       70930  5.027160e+12   3027729.0       0.548389
28               4       70951  1.427666e+11    431244.0       0.767680
29               4       70993  3.048958e+11    792433.0       0.485542
...            ...         ...           ...         ...            ...
568125         894      960899  1.667259e+09     81719.0       0.249665
568126         894      960910  1.806333e+10    269817.0       0.248119
568127         894      960920  4.988872e+08     38178.0       0.342276
568128         894      960990  1.988937e+09     77592.0       0.330360
568129         894      961000  2.452440e+10    270161.0       0.336011
568130         894      961100  4.250239e+09    109883.0       0.352008
568131         894      961210  3.656621e+10    339651.0       0.316967
568132         894      961220  5.131857e+08     44568.0       0.258362
568133         894      961310  3.233004e+09     76623.0       0.550666
568134         894      961320  2.130352e+07      5090.0       0.822272
568135         894      961380  4.652634e+09    104599.0       0.425250
568136         894      961390  5.074476e+07      7410.0       0.924176
568137         894      961400  1.696056e+07      6813.0       0.365396
568138         894      961511  7.958024e+08     41203.0       0.468757
568139         894      961519  4.392555e+10    248364.0       0.712098
568140         894      961590  1.853126e+09     84288.0       0.260840
568141         894      961610  6.081727e+11    809570.0       0.927936
568142         894      961620  5.014182e+08     49267.0       0.206580
568143         894      961700  1.987708e+10    182396.0       0.597478
568144         894      961800  1.748528e+08     22464.0       0.346496
568145         894      961900  1.478781e+14  15937042.0       0.582222
568146         894      962000  1.075454e+08     15621.0       0.440731
568147         894      970110  1.938364e+08     21400.0       0.423260
568148         894      970190  2.909122e+10    284358.0       0.359775
568149         894      970200  5.019250e+06      3098.0       0.522969
568150         894      970300  5.326211e+07     12303.0       0.351881
568151         894      970400  5.610802e+06      2752.0       0.740846
568152         894      970500  3.164114e+08     25475.0       0.487555
568153         894      970600  5.063125e+06      3155.0       0.508651
568154         894      999999  1.543934e+14  25206094.0       0.243006

[568155 rows x 5 columns]

In [6]:
data18_grouped_square_sum.to_csv('Market_concentration_index.csv')

In [7]:
classification = pd.read_csv('../mexico/HH/calificacion.csv')

In [8]:
classification

        country_id  product_id  short_term  large_term  market_size  score
0                4       40210           1           1            0      3
1                4       40291           1           1            1      7
2                4       40310           1           1            0      3
3                4       40610           1           1            0      3
4                4       40900           1           1            0      3
5                4       90210           1           1            1      7
6                4       90230           1           1            1      7
7                4      110100           1           1            1      7
8                4      121490           1           1            0      3
9                4      151800           1           1            1      7
10               4      170191           1           1            1      7
11               4      220290           1           1            0      3
12               4      240220           1           1            0      3
13               4      240391           1           1            0      3
14               4      270300           0           0            1      4
15               4      270500           0           0            1      4
16               4      271121           1           1            0      3
17               4      300670           1           1            1      7
18               4      320300           1           1            0      3
19               4      340120           1           1            0      3
20               4      391729           1           1            0      3
21               4      401140           1           1            0      3
22               4      401150           1           1            0      3
23               4      401211           0           0            1      4
24               4      420232           1           1            0      3
25               4      482390           1           1            1      7
26               4      580810           0           0            1      4
27               4      620640           1           1            0      3
28               4      640320           1           1            1      7
29               4      680100           1           1            1      7
...            ...         ...         ...         ...          ...    ...
287973         894      950810           1           1            0      3
287974         894      960190           1           1            0      3
287975         894      960200           1           1            0      3
287976         894      960310           1           1            0      3
287977         894      960340           1           1            0      3
287978         894      960350           1           1            0      3
287979         894      960400           1           1            0      3
287980         894      960610           1           1            0      3
287981         894      960622           1           1            0      3
287982         894      960629           1           1            0      3
287983         894      960711           1           1            0      3
287984         894      960719           1           1            0      3
287985         894      960720           1           1            0      3
287986         894      960840           1           1            0      3
287987         894      960850           1           1            0      3
287988         894      960910           1           1            0      3
287989         894      960920           1           1            0      3
287990         894      961000           1           1            0      3
287991         894      961100           1           1            0      3
287992         894      961210           1           1            0      3
287993         894      961220           1           1            0      3
287994         894      961310           1           1            0      3
287995         894      961380           1           1            0      3
287996         894      961390           1           1            0      3
287997         894      961610           1           1            0      3
287998         894      961800           1           1            0      3
287999         894      970190           1           1            0      3
288000         894      970200           1           1            0      3
288001         894      970400           1           1            0      3
288002         894      970500           1           1            0      3

[288003 rows x 6 columns]

In [9]:
joined_result = pd.merge(classification,
                 data18_grouped_square_sum,
                 how = 'left',
                 on=['country_id','product_id'])

joined_result['data_18'] = joined_result['concentration'].notnull()  * 1


joined_result

,country_id,product_id,short_term,large_term,market_size,score,value_sqaure,value,concentration,data_18
0,4,40210,1,1,0,3,9.905362e+14,8.568558e+07,0.134913,1
1,4,40291,1,1,1,7,9.302692e+14,4.423850e+07,0.475344,1
2,4,40310,1,1,0,3,1.883667e+14,1.374370e+07,0.997233,1
3,4,40610,1,1,0,3,2.834348e+12,3.889723e+06,0.187334,1
4,4,40900,1,1,0,3,3.607880e+10,2.891110e+05,0.431641,1
5,4,90210,1,1,1,7,8.324681e+15,1.210118e+08,0.568476,1
6,4,90230,1,1,1,7,2.292077e+16,1.712089e+08,0.781946,1
7,4,110100,1,1,1,7,1.125133e+18,1.528949e+09,0.481302,1
8,4,121490,1,1,0,3,1.068459e+14,1.988829e+07,0.270124,1
9,4,151800,1,1,1,7,3.025612e+17,7.892449e+08,0.485724,1
10,4,170191,1,1,1,7,1.286013e+17,4.052956e+08,0.782891,1
11,4,220290,1,1,0,3,6.208277e+14,3.234794e+07,0.593305,1
12,4,240220,1,1,0,3,3.314218e+15,1.032007e+08,0.311183,1
13,4,240391,1,1,0,3,3.121566e+13,6.548794e+06,0.727863,1
14,4,270300,0,0,1,4,6.505113e+17,1.252496e+09,0.414669,1
15,4,270500,0,0,1,4,1.732394e+15,4.354726e+07,0.913535,1
16,4,271121,1,1,0,3,5.523514e+16,4.271114e+08,0.302784,1
17,4,300670,1,1,1,7,6.706790e+15,1.792496e+08,0.208736,1
18,4,320300,1,1,0,3,5.058288e+14,3.013616e+07,0.556965,1
19,4,340120,1,1,0,3,1.183584e+14,2.388551e+07,0.207458,1
20,4,391729,1,1,0,3,6.712768e+12,4.184347e+06,0.383395,1
21,4,401140,1,1,0,3,5.730515e+13,1.364372e+07,0.307842,1
22,4,401150,1,1,0,3,1.162325e+13,4.875344e+06,0.489009,1
23,4,401211,0,0,1,4,4.381498e+16,2.380271e+08,0.773339,1
24,4,420232,1,1,0,3,4.590050e+14,3.962360e+07,0.292354,1
25,4,482390,1,1,1,7,6.522709e+15,1.343182e+08,0.361542,1
26,4,580810,0,0,1,4,5.265510e+16,2.754652e+08,0.693916,1
27,4,620640,1,1,0,3,2.441718e+14,2.474061e+07,0.398910,1
28,4,640320,1,1,1,7,2.438331e+15,7.557536e+07,0.426906,1
29,4,680100,1,1,1,7,1.410983e+17,6.066222e+08,0.383429,1
...,...,...,...,...,...,...,...,...,...,...
287973,894,950810,1,1,0,3,NaN,NaN,NaN,0
287974,894,960190,1,1,0,3,1.583152e+08,2.095200e+04,0.360638,1
287975,894,960200,1,1,0,3,1.145138e+09,3.542500e+04,0.912511,1
287976,894,960310,1,1,0,3,4.340209e+10,4.302400e+05,0.234471,1
287977,894,960340,1,1,0,3,9.123737e+10,5.023980e+05,0.361474,1
287978,894,960350,1,1,0,3,8.147271e+10,4.119900e+05,0.479997,1
287979,894,960400,1,1,0,3,3.975628e+08,2.891400e+04,0.475543,1
287980,894,960610,1,1,0,3,2.967593e+09,5.817400e+04,0.876893,1
287981,894,960622,1,1,0,3,2.767476e+07,7.291000e+03,0.520607,1
287982,894,960629,1,1,0,3,3.974163e+10,2.058450e+05,0.937918,1
287983,894,960711,1,1,0,3,8.039319e+08,4.823200e+04,0.345580,1
287984,894,960719,1,1,0,3,3.747397e+09,8.599500e+04,0.506738,1
287985,894,960720,1,1,0,3,4.419017e+09,6.896500e+04,0.929112,1
287986,894,960840,1,1,0,3,1.683160e+08,1.774100e+04,0.534773,1
287987,894,960850,1,1,0,3,1.383536e+09,5.110600e+04,0.529721,1
287988,894,960910,1,1,0,3,1.806333e+10,2.698170e+05,0.248119,1
287989,894,960920,1,1,0,3,4.988872e+08,3.817800e+04,0.342276,1
287990,894,961000,1,1,0,3,2.452440e+10,2.701610e+05,0.336011,1
287991,894,961100,1,1,0,3,4.250239e+09,1.098830e+05,0.352008,1
287992,894,961210,1,1,0,3,3.656621e+10,3.396510e+05,0.316967,1
287993,894,961220,1,1,0,3,5.131857e+08,4.456800e+04,0.258362,1
287994,894,961310,1,1,0,3,3.233004e+09,7.662300e+04,0.550666,1
287995,894,961380,1,1,0,3,4.652634e+09,1.045990e+05,0.425250,1
287996,894,961390,1,1,0,3,5.074476e+07,7.410000e+03,0.924176,1
287997,894,961610,1,1,0,3,6.081727e+11,8.095700e+05,0.927936,1
287998,894,961800,1,1,0,3,1.748528e+08,2.246400e+04,0.346496,1
287999,894,970190,1,1,0,3,2.909122e+10,2.843580e+05,0.359775,1
288000,894,970200,1,1,0,3,5.019250e+06,3.098000e+03,0.522969,1
288001,894,970400,1,1,0,3,5.610802e+06,2.752000e+03,0.740846,1
288002,894,970500,1,1,0,3,3.164114e+08,2.547500e+04,0.487555,1

In [43]:
data17 = pd.read_csv('../mexico/HH/2017_product_country.csv')

data17["value_sqaure"] = data17['value'] ** 2

data17_grouped = (data17.groupby(['country_id', 'product_id']))

data17_grouped_square_sum = data17_grouped['value_sqaure', 'value'].agg('sum').reset_index()

data17_grouped_square_sum['concentration'] = data17_grouped_square_sum["value_sqaure"] / (data17_grouped_square_sum["value"])**2

data17_grouped_square_sum = data17_grouped_square_sum[['country_id', 'product_id', 'concentration']]

In [11]:
country_list = list(data17_grouped_square_sum['country_id'].drop_duplicates())

dict17 = {}

for i in country_list:
    prod_list = list(data17_grouped_square_sum.loc[data17_grouped_square_sum['country_id'] == i]['product_id'].drop_duplicates())
    dict17.update({i: prod_list})

In [13]:
joined_result

,country_id,product_id,short_term,large_term,market_size,score,value_sqaure,value,concentration,data_18
0,4,40210,1,1,0,3,9.905362e+14,8.568558e+07,0.134913,1
1,4,40291,1,1,1,7,9.302692e+14,4.423850e+07,0.475344,1
2,4,40310,1,1,0,3,1.883667e+14,1.374370e+07,0.997233,1
3,4,40610,1,1,0,3,2.834348e+12,3.889723e+06,0.187334,1
4,4,40900,1,1,0,3,3.607880e+10,2.891110e+05,0.431641,1
5,4,90210,1,1,1,7,8.324681e+15,1.210118e+08,0.568476,1
6,4,90230,1,1,1,7,2.292077e+16,1.712089e+08,0.781946,1
7,4,110100,1,1,1,7,1.125133e+18,1.528949e+09,0.481302,1
8,4,121490,1,1,0,3,1.068459e+14,1.988829e+07,0.270124,1
9,4,151800,1,1,1,7,3.025612e+17,7.892449e+08,0.485724,1
10,4,170191,1,1,1,7,1.286013e+17,4.052956e+08,0.782891,1
11,4,220290,1,1,0,3,6.208277e+14,3.234794e+07,0.593305,1
12,4,240220,1,1,0,3,3.314218e+15,1.032007e+08,0.311183,1
13,4,240391,1,1,0,3,3.121566e+13,6.548794e+06,0.727863,1
14,4,270300,0,0,1,4,6.505113e+17,1.252496e+09,0.414669,1
15,4,270500,0,0,1,4,1.732394e+15,4.354726e+07,0.913535,1
16,4,271121,1,1,0,3,5.523514e+16,4.271114e+08,0.302784,1
17,4,300670,1,1,1,7,6.706790e+15,1.792496e+08,0.208736,1
18,4,320300,1,1,0,3,5.058288e+14,3.013616e+07,0.556965,1
19,4,340120,1,1,0,3,1.183584e+14,2.388551e+07,0.207458,1
20,4,391729,1,1,0,3,6.712768e+12,4.184347e+06,0.383395,1
21,4,401140,1,1,0,3,5.730515e+13,1.364372e+07,0.307842,1
22,4,401150,1,1,0,3,1.162325e+13,4.875344e+06,0.489009,1
23,4,401211,0,0,1,4,4.381498e+16,2.380271e+08,0.773339,1
24,4,420232,1,1,0,3,4.590050e+14,3.962360e+07,0.292354,1
25,4,482390,1,1,1,7,6.522709e+15,1.343182e+08,0.361542,1
26,4,580810,0,0,1,4,5.265510e+16,2.754652e+08,0.693916,1
27,4,620640,1,1,0,3,2.441718e+14,2.474061e+07,0.398910,1
28,4,640320,1,1,1,7,2.438331e+15,7.557536e+07,0.426906,1
29,4,680100,1,1,1,7,1.410983e+17,6.066222e+08,0.383429,1
...,...,...,...,...,...,...,...,...,...,...
287973,894,950810,1,1,0,3,NaN,NaN,NaN,0
287974,894,960190,1,1,0,3,1.583152e+08,2.095200e+04,0.360638,1
287975,894,960200,1,1,0,3,1.145138e+09,3.542500e+04,0.912511,1
287976,894,960310,1,1,0,3,4.340209e+10,4.302400e+05,0.234471,1
287977,894,960340,1,1,0,3,9.123737e+10,5.023980e+05,0.361474,1
287978,894,960350,1,1,0,3,8.147271e+10,4.119900e+05,0.479997,1
287979,894,960400,1,1,0,3,3.975628e+08,2.891400e+04,0.475543,1
287980,894,960610,1,1,0,3,2.967593e+09,5.817400e+04,0.876893,1
287981,894,960622,1,1,0,3,2.767476e+07,7.291000e+03,0.520607,1
287982,894,960629,1,1,0,3,3.974163e+10,2.058450e+05,0.937918,1
287983,894,960711,1,1,0,3,8.039319e+08,4.823200e+04,0.345580,1
287984,894,960719,1,1,0,3,3.747397e+09,8.599500e+04,0.506738,1
287985,894,960720,1,1,0,3,4.419017e+09,6.896500e+04,0.929112,1
287986,894,960840,1,1,0,3,1.683160e+08,1.774100e+04,0.534773,1
287987,894,960850,1,1,0,3,1.383536e+09,5.110600e+04,0.529721,1
287988,894,960910,1,1,0,3,1.806333e+10,2.698170e+05,0.248119,1
287989,894,960920,1,1,0,3,4.988872e+08,3.817800e+04,0.342276,1
287990,894,961000,1,1,0,3,2.452440e+10,2.701610e+05,0.336011,1
287991,894,961100,1,1,0,3,4.250239e+09,1.098830e+05,0.352008,1
287992,894,961210,1,1,0,3,3.656621e+10,3.396510e+05,0.316967,1
287993,894,961220,1,1,0,3,5.131857e+08,4.456800e+04,0.258362,1
287994,894,961310,1,1,0,3,3.233004e+09,7.662300e+04,0.550666,1
287995,894,961380,1,1,0,3,4.652634e+09,1.045990e+05,0.425250,1
287996,894,961390,1,1,0,3,5.074476e+07,7.410000e+03,0.924176,1
287997,894,961610,1,1,0,3,6.081727e+11,8.095700e+05,0.927936,1
287998,894,961800,1,1,0,3,1.748528e+08,2.246400e+04,0.346496,1
287999,894,970190,1,1,0,3,2.909122e+10,2.843580e+05,0.359775,1
288000,894,970200,1,1,0,3,5.019250e+06,3.098000e+03,0.522969,1
288001,894,970400,1,1,0,3,5.610802e+06,2.752000e+03,0.740846,1
288002,894,970500,1,1,0,3,3.164114e+08,2.547500e+04,0.487555,1

In [14]:
joined_result

df_no18 = joined_result[['country_id', 'product_id']].loc[joined_result['data_18'] == 0]

df_no18

        country_id  product_id
44               8       20727
70               8       70992
112              8      110419
117              8      120921
120              8      121490
121              8      130239
131              8      152190
165              8      200950
172              8      220290
175              8      220840
179              8      251110
183              8      251612
185              8      253010
191              8      282300
192              8      282810
194              8      285300
201              8      300210
209              8      310310
213              8      320500
253              8      350400
261              8      381230
266              8      382370
268              8      382490
269              8      390290
272              8      390490
275              8      390760
278              8      390930
279              8      391110
291              8      392114
311              8      401161
...            ...         ...
286192         894       20312
286210         894       30369
286272         894       71360
286331         894      100790
286374         894      152110
286470         894      280512
286592         894      292529
286600         894      293420
286674         894      370120
286678         894      370310
286715         894      390320
286736         894      391510
286810         894      440131
286887         894      511190
286914         894      530310
286989         894      580126
287013         894      600410
287206         894      701400
287224         894      710692
287236         894      720711
287358         894      741011
287390         894      780420
287393         894      790120
287402         894      811010
287571         894      844511
287573         894      844530
287579         894      844831
287613         894      846130
287696         894      850231
287973         894      950810

[47117 rows x 2 columns]

In [15]:
def check_in17(a,b):
    if b in list(dict17.keys()):
        return ((a in dict17[b]) * 1)
    
    else:
        return (0)

df_no18['data_2017'] = df_no18[['product_id','country_id']].apply(lambda x: check_in17(*x), axis=1)

df_no18

        country_id  product_id  data_2017
44               8       20727          1
70               8       70992          1
112              8      110419          1
117              8      120921          1
120              8      121490          0
121              8      130239          0
131              8      152190          1
165              8      200950          0
172              8      220290          0
175              8      220840          0
179              8      251110          0
183              8      251612          1
185              8      253010          1
191              8      282300          0
192              8      282810          1
194              8      285300          0
201              8      300210          0
209              8      310310          0
213              8      320500          0
253              8      350400          0
261              8      381230          0
266              8      382370          1
268              8      382490          0
269              8      390290          0
272              8      390490          1
275              8      390760          0
278              8      390930          0
279              8      391110          0
291              8      392114          1
311              8      401161          0
...            ...         ...        ...
286192         894       20312          1
286210         894       30369          1
286272         894       71360          1
286331         894      100790          1
286374         894      152110          1
286470         894      280512          1
286592         894      292529          1
286600         894      293420          1
286674         894      370120          1
286678         894      370310          1
286715         894      390320          1
286736         894      391510          1
286810         894      440131          1
286887         894      511190          1
286914         894      530310          1
286989         894      580126          1
287013         894      600410          1
287206         894      701400          1
287224         894      710692          1
287236         894      720711          1
287358         894      741011          1
287390         894      780420          1
287393         894      790120          1
287402         894      811010          1
287571         894      844511          1
287573         894      844530          1
287579         894      844831          1
287613         894      846130          1
287696         894      850231          1
287973         894      950810          1

[47117 rows x 3 columns]

In [71]:
# print (df_no18['data_2017'].sum())

no_data_loc = df_no18.loc[df_no18['data_2017'] == 0].index 

data_17_loc = df_no18.loc[df_no18['data_2017'] == 1].index

In [76]:
no_data_loc

Int64Index([   120,    121,    165,    172,    175,    179,    191,    194,
               201,    209,
            ...
            285280, 285317, 285523, 285602, 285823, 285923, 285967, 285999,
            286054, 286129],
           dtype='int64', length=13127)

In [73]:
joined_result

,country_id,product_id,short_term,large_term,market_size,score,value_sqaure,value,concentration,data_18,no_data,filter3_result
0,4,40210,1,1,0,3,9.905362e+14,8.568558e+07,0.134913,1,0,1
1,4,40291,1,1,1,7,9.302692e+14,4.423850e+07,0.475344,1,0,1
3,4,40610,1,1,0,3,2.834348e+12,3.889723e+06,0.187334,1,0,1
5,4,90210,1,1,1,7,8.324681e+15,1.210118e+08,0.568476,1,0,1
7,4,110100,1,1,1,7,1.125133e+18,1.528949e+09,0.481302,1,0,1
8,4,121490,1,1,0,3,1.068459e+14,1.988829e+07,0.270124,1,0,1
9,4,151800,1,1,1,7,3.025612e+17,7.892449e+08,0.485724,1,0,1
12,4,240220,1,1,0,3,3.314218e+15,1.032007e+08,0.311183,1,0,1
14,4,270300,0,0,1,4,6.505113e+17,1.252496e+09,0.414669,1,0,1
16,4,271121,1,1,0,3,5.523514e+16,4.271114e+08,0.302784,1,0,1
17,4,300670,1,1,1,7,6.706790e+15,1.792496e+08,0.208736,1,0,1
19,4,340120,1,1,0,3,1.183584e+14,2.388551e+07,0.207458,1,0,1
20,4,391729,1,1,0,3,6.712768e+12,4.184347e+06,0.383395,1,0,1
21,4,401140,1,1,0,3,5.730515e+13,1.364372e+07,0.307842,1,0,1
24,4,420232,1,1,0,3,4.590050e+14,3.962360e+07,0.292354,1,0,1
25,4,482390,1,1,1,7,6.522709e+15,1.343182e+08,0.361542,1,0,1
27,4,620640,1,1,0,3,2.441718e+14,2.474061e+07,0.398910,1,0,1
28,4,640320,1,1,1,7,2.438331e+15,7.557536e+07,0.426906,1,0,1
29,4,680100,1,1,1,7,1.410983e+17,6.066222e+08,0.383429,1,0,1
30,4,721631,1,1,0,3,3.399179e+14,3.415169e+07,0.291440,1,0,1
31,4,830140,1,1,0,3,2.238175e+16,2.533913e+08,0.348587,1,0,1
33,4,843360,1,1,0,3,3.755952e+13,1.348811e+07,0.206451,1,0,1
34,4,845720,1,1,1,7,2.737105e+13,1.038264e+07,0.253908,1,0,1
35,4,851150,1,1,0,3,1.528816e+14,2.279010e+07,0.294349,1,0,1
37,4,870520,1,1,1,7,2.113566e+13,7.201440e+06,0.407547,1,0,1
40,4,901819,1,1,0,3,3.788668e+14,4.432850e+07,0.192806,1,0,1
41,4,901890,1,1,0,3,8.190382e+16,4.901623e+08,0.340898,1,0,1
42,4,902830,1,1,0,3,1.322512e+17,5.785059e+08,0.395170,1,0,1
50,8,40120,1,1,0,3,1.179696e+13,5.768654e+06,0.354504,1,0,1
53,8,40210,1,1,0,3,5.013273e+10,3.787130e+05,0.349543,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
287910,894,902780,1,1,0,3,3.694655e+12,3.327971e+06,0.333591,1,0,1
287911,894,902810,1,1,0,3,9.682382e+07,1.705300e+04,0.332951,1,0,1
287915,894,902910,1,1,0,3,1.062888e+09,7.286400e+04,0.200199,1,0,1
287916,894,902920,1,1,0,3,4.574197e+09,1.438880e+05,0.220936,1,0,1
287917,894,903032,1,1,0,3,1.545099e+11,6.686900e+05,0.345547,1,0,1
287918,894,903033,1,1,0,3,1.626105e+10,3.154560e+05,0.163407,1,0,1
287919,894,903110,1,1,0,3,7.368144e+09,1.369780e+05,0.392696,1,0,1
287924,894,903290,1,1,0,3,2.650146e+11,1.012169e+06,0.258681,1,0,1
287925,894,903300,1,1,0,3,7.210925e+11,1.400735e+06,0.367518,1,0,1
287926,894,910111,1,1,0,3,2.157954e+08,2.509100e+04,0.342773,1,0,1
287941,894,920510,1,1,0,3,1.700730e+07,6.763000e+03,0.371840,1,0,1
287942,894,920890,1,1,0,3,1.834460e+07,7.687000e+03,0.310452,1,0,1
287951,894,940130,1,1,0,3,2.100851e+11,8.342760e+05,0.301839,1,0,1
287955,894,940290,1,1,0,3,2.403317e+12,3.238138e+06,0.229203,1,0,1
287959,894,940520,1,1,0,3,2.024866e+10,2.575370e+05,0.305293,1,0,1
287962,894,940591,1,1,0,3,8.997949e+08,5.157000e+04,0.338337,1,0,1
287967,894,950662,1,1,0,3,1.540141e+10,2.312410e+05,0.288025,1,0,1
287968,894,950669,1,1,0,3,2.514709e+09,9.361700e+04,0.286932,1,0,1
287974,894,960190,1,1,0,3,1.583152e+08,2.095200e+04,0.360638,1,0,1
287976,894,960310,1,1,0,3,4.340209e+10,4.302400e+05,0.234471,1,0,1
287977,894,960340,1,1,0,3,9.123737e+10,5.023980e+05,0.361474,1,0,1
287983,894,960711,1,1,0,3,8.039319e+08,4.823200e+04,0.345580,1,0,1
287988,894,960910,1,1,0,3,1.806333e+10,2.698170e+05,0.248119,1,0,1
287989,894,960920,1,1,0,3,4.988872e+08,3.817800e+04,0.342276,1,0,1
287990,894,961000,1,1,0,3,2.452440e+10,2.701610e+05,0.336011,1,0,1
287991,894,961100,1,1,0,3,4.250239e+09,1.098830e+05,0.352008,1,0,1
287992,894,961210,1,1,0,3,3.656621e+10,3.396510e+05,0.316967,1,0,1
287993,894,961220,1,1,0,3,5.131857e+08,4.456800e+04,0.258362,1,0,1
287998,894,961800,1,1,0,3,1.748528e+08,2.246400e+04,0.346496,1,0,1
287999,894,970190,1,1,0,3,2.909122e+10,2.843580e+05,0.359775,1,0,1

In [75]:
joined_result['no_data'] = 0

# joined_result['no_data'].loc[no_data_loc] = 1

print (joined_result['no_data'].sum())

0

/Users/huangruijie/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [44]:
acc = 1

for i in (list(data_17_loc.values)):
    
    cid, pid = joined_result[['country_id', 'product_id']].loc[i]

    acc += 1 

    if acc % 100 == 0:
        print (acc//100)

    result = data17_grouped_square_sum['concentration'][data17_grouped_square_sum['country_id'] == cid][data17_grouped_square_sum['product_id'] == pid].iloc[0]

    joined_result['concentration'].loc[i] = result

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339

In [70]:

print (joined_result['no_data'].sum())

0

In [45]:
joined_result

,country_id,product_id,short_term,large_term,market_size,score,value_sqaure,value,concentration,data_18,no_data
0,4,40210,1,1,0,3,9.905362e+14,8.568558e+07,0.134913,1,0
1,4,40291,1,1,1,7,9.302692e+14,4.423850e+07,0.475344,1,0
2,4,40310,1,1,0,3,1.883667e+14,1.374370e+07,0.997233,1,0
3,4,40610,1,1,0,3,2.834348e+12,3.889723e+06,0.187334,1,0
4,4,40900,1,1,0,3,3.607880e+10,2.891110e+05,0.431641,1,0
5,4,90210,1,1,1,7,8.324681e+15,1.210118e+08,0.568476,1,0
6,4,90230,1,1,1,7,2.292077e+16,1.712089e+08,0.781946,1,0
7,4,110100,1,1,1,7,1.125133e+18,1.528949e+09,0.481302,1,0
8,4,121490,1,1,0,3,1.068459e+14,1.988829e+07,0.270124,1,0
9,4,151800,1,1,1,7,3.025612e+17,7.892449e+08,0.485724,1,0
10,4,170191,1,1,1,7,1.286013e+17,4.052956e+08,0.782891,1,0
11,4,220290,1,1,0,3,6.208277e+14,3.234794e+07,0.593305,1,0
12,4,240220,1,1,0,3,3.314218e+15,1.032007e+08,0.311183,1,0
13,4,240391,1,1,0,3,3.121566e+13,6.548794e+06,0.727863,1,0
14,4,270300,0,0,1,4,6.505113e+17,1.252496e+09,0.414669,1,0
15,4,270500,0,0,1,4,1.732394e+15,4.354726e+07,0.913535,1,0
16,4,271121,1,1,0,3,5.523514e+16,4.271114e+08,0.302784,1,0
17,4,300670,1,1,1,7,6.706790e+15,1.792496e+08,0.208736,1,0
18,4,320300,1,1,0,3,5.058288e+14,3.013616e+07,0.556965,1,0
19,4,340120,1,1,0,3,1.183584e+14,2.388551e+07,0.207458,1,0
20,4,391729,1,1,0,3,6.712768e+12,4.184347e+06,0.383395,1,0
21,4,401140,1,1,0,3,5.730515e+13,1.364372e+07,0.307842,1,0
22,4,401150,1,1,0,3,1.162325e+13,4.875344e+06,0.489009,1,0
23,4,401211,0,0,1,4,4.381498e+16,2.380271e+08,0.773339,1,0
24,4,420232,1,1,0,3,4.590050e+14,3.962360e+07,0.292354,1,0
25,4,482390,1,1,1,7,6.522709e+15,1.343182e+08,0.361542,1,0
26,4,580810,0,0,1,4,5.265510e+16,2.754652e+08,0.693916,1,0
27,4,620640,1,1,0,3,2.441718e+14,2.474061e+07,0.398910,1,0
28,4,640320,1,1,1,7,2.438331e+15,7.557536e+07,0.426906,1,0
29,4,680100,1,1,1,7,1.410983e+17,6.066222e+08,0.383429,1,0
...,...,...,...,...,...,...,...,...,...,...,...
287973,894,950810,1,1,0,3,NaN,NaN,0.707660,0,0
287974,894,960190,1,1,0,3,1.583152e+08,2.095200e+04,0.360638,1,0
287975,894,960200,1,1,0,3,1.145138e+09,3.542500e+04,0.912511,1,0
287976,894,960310,1,1,0,3,4.340209e+10,4.302400e+05,0.234471,1,0
287977,894,960340,1,1,0,3,9.123737e+10,5.023980e+05,0.361474,1,0
287978,894,960350,1,1,0,3,8.147271e+10,4.119900e+05,0.479997,1,0
287979,894,960400,1,1,0,3,3.975628e+08,2.891400e+04,0.475543,1,0
287980,894,960610,1,1,0,3,2.967593e+09,5.817400e+04,0.876893,1,0
287981,894,960622,1,1,0,3,2.767476e+07,7.291000e+03,0.520607,1,0
287982,894,960629,1,1,0,3,3.974163e+10,2.058450e+05,0.937918,1,0
287983,894,960711,1,1,0,3,8.039319e+08,4.823200e+04,0.345580,1,0
287984,894,960719,1,1,0,3,3.747397e+09,8.599500e+04,0.506738,1,0
287985,894,960720,1,1,0,3,4.419017e+09,6.896500e+04,0.929112,1,0
287986,894,960840,1,1,0,3,1.683160e+08,1.774100e+04,0.534773,1,0
287987,894,960850,1,1,0,3,1.383536e+09,5.110600e+04,0.529721,1,0
287988,894,960910,1,1,0,3,1.806333e+10,2.698170e+05,0.248119,1,0
287989,894,960920,1,1,0,3,4.988872e+08,3.817800e+04,0.342276,1,0
287990,894,961000,1,1,0,3,2.452440e+10,2.701610e+05,0.336011,1,0
287991,894,961100,1,1,0,3,4.250239e+09,1.098830e+05,0.352008,1,0
287992,894,961210,1,1,0,3,3.656621e+10,3.396510e+05,0.316967,1,0
287993,894,961220,1,1,0,3,5.131857e+08,4.456800e+04,0.258362,1,0
287994,894,961310,1,1,0,3,3.233004e+09,7.662300e+04,0.550666,1,0
287995,894,961380,1,1,0,3,4.652634e+09,1.045990e+05,0.425250,1,0
287996,894,961390,1,1,0,3,5.074476e+07,7.410000e+03,0.924176,1,0
287997,894,961610,1,1,0,3,6.081727e+11,8.095700e+05,0.927936,1,0
287998,894,961800,1,1,0,3,1.748528e+08,2.246400e+04,0.346496,1,0
287999,894,970190,1,1,0,3,2.909122e+10,2.843580e+05,0.359775,1,0
288000,894,970200,1,1,0,3,5.019250e+06,3.098000e+03,0.522969,1,0
288001,894,970400,1,1,0,3,5.610802e+06,2.752000e+03,0.740846,1,0
288002,894,970500,1,1,0,3,3.164114e+08,2.547500e+04,0.487555,1,0

In [84]:
joined_result = joined_result.loc[joined_result['concentration'].notnull()]

joined_result

,country_id,product_id,short_term,large_term,market_size,score,value_sqaure,value,concentration,data_18,no_data,filter3_result
0,4,40210,1,1,0,3,9.905362e+14,8.568558e+07,0.134913,1,0,1
1,4,40291,1,1,1,7,9.302692e+14,4.423850e+07,0.475344,1,0,1
3,4,40610,1,1,0,3,2.834348e+12,3.889723e+06,0.187334,1,0,1
5,4,90210,1,1,1,7,8.324681e+15,1.210118e+08,0.568476,1,0,1
7,4,110100,1,1,1,7,1.125133e+18,1.528949e+09,0.481302,1,0,1
8,4,121490,1,1,0,3,1.068459e+14,1.988829e+07,0.270124,1,0,1
9,4,151800,1,1,1,7,3.025612e+17,7.892449e+08,0.485724,1,0,1
12,4,240220,1,1,0,3,3.314218e+15,1.032007e+08,0.311183,1,0,1
14,4,270300,0,0,1,4,6.505113e+17,1.252496e+09,0.414669,1,0,1
16,4,271121,1,1,0,3,5.523514e+16,4.271114e+08,0.302784,1,0,1
17,4,300670,1,1,1,7,6.706790e+15,1.792496e+08,0.208736,1,0,1
19,4,340120,1,1,0,3,1.183584e+14,2.388551e+07,0.207458,1,0,1
20,4,391729,1,1,0,3,6.712768e+12,4.184347e+06,0.383395,1,0,1
21,4,401140,1,1,0,3,5.730515e+13,1.364372e+07,0.307842,1,0,1
24,4,420232,1,1,0,3,4.590050e+14,3.962360e+07,0.292354,1,0,1
25,4,482390,1,1,1,7,6.522709e+15,1.343182e+08,0.361542,1,0,1
27,4,620640,1,1,0,3,2.441718e+14,2.474061e+07,0.398910,1,0,1
28,4,640320,1,1,1,7,2.438331e+15,7.557536e+07,0.426906,1,0,1
29,4,680100,1,1,1,7,1.410983e+17,6.066222e+08,0.383429,1,0,1
30,4,721631,1,1,0,3,3.399179e+14,3.415169e+07,0.291440,1,0,1
31,4,830140,1,1,0,3,2.238175e+16,2.533913e+08,0.348587,1,0,1
33,4,843360,1,1,0,3,3.755952e+13,1.348811e+07,0.206451,1,0,1
34,4,845720,1,1,1,7,2.737105e+13,1.038264e+07,0.253908,1,0,1
35,4,851150,1,1,0,3,1.528816e+14,2.279010e+07,0.294349,1,0,1
37,4,870520,1,1,1,7,2.113566e+13,7.201440e+06,0.407547,1,0,1
40,4,901819,1,1,0,3,3.788668e+14,4.432850e+07,0.192806,1,0,1
41,4,901890,1,1,0,3,8.190382e+16,4.901623e+08,0.340898,1,0,1
42,4,902830,1,1,0,3,1.322512e+17,5.785059e+08,0.395170,1,0,1
50,8,40120,1,1,0,3,1.179696e+13,5.768654e+06,0.354504,1,0,1
53,8,40210,1,1,0,3,5.013273e+10,3.787130e+05,0.349543,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
287910,894,902780,1,1,0,3,3.694655e+12,3.327971e+06,0.333591,1,0,1
287911,894,902810,1,1,0,3,9.682382e+07,1.705300e+04,0.332951,1,0,1
287915,894,902910,1,1,0,3,1.062888e+09,7.286400e+04,0.200199,1,0,1
287916,894,902920,1,1,0,3,4.574197e+09,1.438880e+05,0.220936,1,0,1
287917,894,903032,1,1,0,3,1.545099e+11,6.686900e+05,0.345547,1,0,1
287918,894,903033,1,1,0,3,1.626105e+10,3.154560e+05,0.163407,1,0,1
287919,894,903110,1,1,0,3,7.368144e+09,1.369780e+05,0.392696,1,0,1
287924,894,903290,1,1,0,3,2.650146e+11,1.012169e+06,0.258681,1,0,1
287925,894,903300,1,1,0,3,7.210925e+11,1.400735e+06,0.367518,1,0,1
287926,894,910111,1,1,0,3,2.157954e+08,2.509100e+04,0.342773,1,0,1
287941,894,920510,1,1,0,3,1.700730e+07,6.763000e+03,0.371840,1,0,1
287942,894,920890,1,1,0,3,1.834460e+07,7.687000e+03,0.310452,1,0,1
287951,894,940130,1,1,0,3,2.100851e+11,8.342760e+05,0.301839,1,0,1
287955,894,940290,1,1,0,3,2.403317e+12,3.238138e+06,0.229203,1,0,1
287959,894,940520,1,1,0,3,2.024866e+10,2.575370e+05,0.305293,1,0,1
287962,894,940591,1,1,0,3,8.997949e+08,5.157000e+04,0.338337,1,0,1
287967,894,950662,1,1,0,3,1.540141e+10,2.312410e+05,0.288025,1,0,1
287968,894,950669,1,1,0,3,2.514709e+09,9.361700e+04,0.286932,1,0,1
287974,894,960190,1,1,0,3,1.583152e+08,2.095200e+04,0.360638,1,0,1
287976,894,960310,1,1,0,3,4.340209e+10,4.302400e+05,0.234471,1,0,1
287977,894,960340,1,1,0,3,9.123737e+10,5.023980e+05,0.361474,1,0,1
287983,894,960711,1,1,0,3,8.039319e+08,4.823200e+04,0.345580,1,0,1
287988,894,960910,1,1,0,3,1.806333e+10,2.698170e+05,0.248119,1,0,1
287989,894,960920,1,1,0,3,4.988872e+08,3.817800e+04,0.342276,1,0,1
287990,894,961000,1,1,0,3,2.452440e+10,2.701610e+05,0.336011,1,0,1
287991,894,961100,1,1,0,3,4.250239e+09,1.098830e+05,0.352008,1,0,1
287992,894,961210,1,1,0,3,3.656621e+10,3.396510e+05,0.316967,1,0,1
287993,894,961220,1,1,0,3,5.131857e+08,4.456800e+04,0.258362,1,0,1
287998,894,961800,1,1,0,3,1.748528e+08,2.246400e+04,0.346496,1,0,1
287999,894,970190,1,1,0,3,2.909122e+10,2.843580e+05,0.359775,1,0,1

In [85]:
def filter_3(cate, concen):
    if (cate == 3 and concen < 0.4) or ((cate == 4 or cate == 5 or cate == 6) and concen < 0.5) or (cate == 7 and concen < 0.6):
        return (1)
    
    else:
        return (0)

    
joined_result['filter3_result'] = joined_result[['score','concentration']].apply(lambda x: filter_3(*x), axis=1)

In [86]:
joined_result

,country_id,product_id,short_term,large_term,market_size,score,value_sqaure,value,concentration,data_18,no_data,filter3_result
0,4,40210,1,1,0,3,9.905362e+14,8.568558e+07,0.134913,1,0,1
1,4,40291,1,1,1,7,9.302692e+14,4.423850e+07,0.475344,1,0,1
3,4,40610,1,1,0,3,2.834348e+12,3.889723e+06,0.187334,1,0,1
5,4,90210,1,1,1,7,8.324681e+15,1.210118e+08,0.568476,1,0,1
7,4,110100,1,1,1,7,1.125133e+18,1.528949e+09,0.481302,1,0,1
8,4,121490,1,1,0,3,1.068459e+14,1.988829e+07,0.270124,1,0,1
9,4,151800,1,1,1,7,3.025612e+17,7.892449e+08,0.485724,1,0,1
12,4,240220,1,1,0,3,3.314218e+15,1.032007e+08,0.311183,1,0,1
14,4,270300,0,0,1,4,6.505113e+17,1.252496e+09,0.414669,1,0,1
16,4,271121,1,1,0,3,5.523514e+16,4.271114e+08,0.302784,1,0,1
17,4,300670,1,1,1,7,6.706790e+15,1.792496e+08,0.208736,1,0,1
19,4,340120,1,1,0,3,1.183584e+14,2.388551e+07,0.207458,1,0,1
20,4,391729,1,1,0,3,6.712768e+12,4.184347e+06,0.383395,1,0,1
21,4,401140,1,1,0,3,5.730515e+13,1.364372e+07,0.307842,1,0,1
24,4,420232,1,1,0,3,4.590050e+14,3.962360e+07,0.292354,1,0,1
25,4,482390,1,1,1,7,6.522709e+15,1.343182e+08,0.361542,1,0,1
27,4,620640,1,1,0,3,2.441718e+14,2.474061e+07,0.398910,1,0,1
28,4,640320,1,1,1,7,2.438331e+15,7.557536e+07,0.426906,1,0,1
29,4,680100,1,1,1,7,1.410983e+17,6.066222e+08,0.383429,1,0,1
30,4,721631,1,1,0,3,3.399179e+14,3.415169e+07,0.291440,1,0,1
31,4,830140,1,1,0,3,2.238175e+16,2.533913e+08,0.348587,1,0,1
33,4,843360,1,1,0,3,3.755952e+13,1.348811e+07,0.206451,1,0,1
34,4,845720,1,1,1,7,2.737105e+13,1.038264e+07,0.253908,1,0,1
35,4,851150,1,1,0,3,1.528816e+14,2.279010e+07,0.294349,1,0,1
37,4,870520,1,1,1,7,2.113566e+13,7.201440e+06,0.407547,1,0,1
40,4,901819,1,1,0,3,3.788668e+14,4.432850e+07,0.192806,1,0,1
41,4,901890,1,1,0,3,8.190382e+16,4.901623e+08,0.340898,1,0,1
42,4,902830,1,1,0,3,1.322512e+17,5.785059e+08,0.395170,1,0,1
50,8,40120,1,1,0,3,1.179696e+13,5.768654e+06,0.354504,1,0,1
53,8,40210,1,1,0,3,5.013273e+10,3.787130e+05,0.349543,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
287910,894,902780,1,1,0,3,3.694655e+12,3.327971e+06,0.333591,1,0,1
287911,894,902810,1,1,0,3,9.682382e+07,1.705300e+04,0.332951,1,0,1
287915,894,902910,1,1,0,3,1.062888e+09,7.286400e+04,0.200199,1,0,1
287916,894,902920,1,1,0,3,4.574197e+09,1.438880e+05,0.220936,1,0,1
287917,894,903032,1,1,0,3,1.545099e+11,6.686900e+05,0.345547,1,0,1
287918,894,903033,1,1,0,3,1.626105e+10,3.154560e+05,0.163407,1,0,1
287919,894,903110,1,1,0,3,7.368144e+09,1.369780e+05,0.392696,1,0,1
287924,894,903290,1,1,0,3,2.650146e+11,1.012169e+06,0.258681,1,0,1
287925,894,903300,1,1,0,3,7.210925e+11,1.400735e+06,0.367518,1,0,1
287926,894,910111,1,1,0,3,2.157954e+08,2.509100e+04,0.342773,1,0,1
287941,894,920510,1,1,0,3,1.700730e+07,6.763000e+03,0.371840,1,0,1
287942,894,920890,1,1,0,3,1.834460e+07,7.687000e+03,0.310452,1,0,1
287951,894,940130,1,1,0,3,2.100851e+11,8.342760e+05,0.301839,1,0,1
287955,894,940290,1,1,0,3,2.403317e+12,3.238138e+06,0.229203,1,0,1
287959,894,940520,1,1,0,3,2.024866e+10,2.575370e+05,0.305293,1,0,1
287962,894,940591,1,1,0,3,8.997949e+08,5.157000e+04,0.338337,1,0,1
287967,894,950662,1,1,0,3,1.540141e+10,2.312410e+05,0.288025,1,0,1
287968,894,950669,1,1,0,3,2.514709e+09,9.361700e+04,0.286932,1,0,1
287974,894,960190,1,1,0,3,1.583152e+08,2.095200e+04,0.360638,1,0,1
287976,894,960310,1,1,0,3,4.340209e+10,4.302400e+05,0.234471,1,0,1
287977,894,960340,1,1,0,3,9.123737e+10,5.023980e+05,0.361474,1,0,1
287983,894,960711,1,1,0,3,8.039319e+08,4.823200e+04,0.345580,1,0,1
287988,894,960910,1,1,0,3,1.806333e+10,2.698170e+05,0.248119,1,0,1
287989,894,960920,1,1,0,3,4.988872e+08,3.817800e+04,0.342276,1,0,1
287990,894,961000,1,1,0,3,2.452440e+10,2.701610e+05,0.336011,1,0,1
287991,894,961100,1,1,0,3,4.250239e+09,1.098830e+05,0.352008,1,0,1
287992,894,961210,1,1,0,3,3.656621e+10,3.396510e+05,0.316967,1,0,1
287993,894,961220,1,1,0,3,5.131857e+08,4.456800e+04,0.258362,1,0,1
287998,894,961800,1,1,0,3,1.748528e+08,2.246400e+04,0.346496,1,0,1
287999,894,970190,1,1,0,3,2.909122e+10,2.843580e+05,0.359775,1,0,1

In [ ]:
joined_result['filter3_result'].sum()

In [87]:
joined_result.to_csv('filter3_result.csv')

In [49]:
result_NaN = pd.merge(classification,
                 data18_grouped_square_sum,
                 how = 'left',
                 on=['country_id','product_id'])

result_NaN = result_NaN[result_NaN['concentration'].isnull()]

In [50]:
result_NaN.to_csv('Null_Rows.csv')

In [88]:
joined_result = joined_result.loc[joined_result['filter3_result'] == 1]

In [89]:
joined_result

,country_id,product_id,short_term,large_term,market_size,score,value_sqaure,value,concentration,data_18,no_data,filter3_result
0,4,40210,1,1,0,3,9.905362e+14,8.568558e+07,0.134913,1,0,1
1,4,40291,1,1,1,7,9.302692e+14,4.423850e+07,0.475344,1,0,1
3,4,40610,1,1,0,3,2.834348e+12,3.889723e+06,0.187334,1,0,1
5,4,90210,1,1,1,7,8.324681e+15,1.210118e+08,0.568476,1,0,1
7,4,110100,1,1,1,7,1.125133e+18,1.528949e+09,0.481302,1,0,1
8,4,121490,1,1,0,3,1.068459e+14,1.988829e+07,0.270124,1,0,1
9,4,151800,1,1,1,7,3.025612e+17,7.892449e+08,0.485724,1,0,1
12,4,240220,1,1,0,3,3.314218e+15,1.032007e+08,0.311183,1,0,1
14,4,270300,0,0,1,4,6.505113e+17,1.252496e+09,0.414669,1,0,1
16,4,271121,1,1,0,3,5.523514e+16,4.271114e+08,0.302784,1,0,1
17,4,300670,1,1,1,7,6.706790e+15,1.792496e+08,0.208736,1,0,1
19,4,340120,1,1,0,3,1.183584e+14,2.388551e+07,0.207458,1,0,1
20,4,391729,1,1,0,3,6.712768e+12,4.184347e+06,0.383395,1,0,1
21,4,401140,1,1,0,3,5.730515e+13,1.364372e+07,0.307842,1,0,1
24,4,420232,1,1,0,3,4.590050e+14,3.962360e+07,0.292354,1,0,1
25,4,482390,1,1,1,7,6.522709e+15,1.343182e+08,0.361542,1,0,1
27,4,620640,1,1,0,3,2.441718e+14,2.474061e+07,0.398910,1,0,1
28,4,640320,1,1,1,7,2.438331e+15,7.557536e+07,0.426906,1,0,1
29,4,680100,1,1,1,7,1.410983e+17,6.066222e+08,0.383429,1,0,1
30,4,721631,1,1,0,3,3.399179e+14,3.415169e+07,0.291440,1,0,1
31,4,830140,1,1,0,3,2.238175e+16,2.533913e+08,0.348587,1,0,1
33,4,843360,1,1,0,3,3.755952e+13,1.348811e+07,0.206451,1,0,1
34,4,845720,1,1,1,7,2.737105e+13,1.038264e+07,0.253908,1,0,1
35,4,851150,1,1,0,3,1.528816e+14,2.279010e+07,0.294349,1,0,1
37,4,870520,1,1,1,7,2.113566e+13,7.201440e+06,0.407547,1,0,1
40,4,901819,1,1,0,3,3.788668e+14,4.432850e+07,0.192806,1,0,1
41,4,901890,1,1,0,3,8.190382e+16,4.901623e+08,0.340898,1,0,1
42,4,902830,1,1,0,3,1.322512e+17,5.785059e+08,0.395170,1,0,1
50,8,40120,1,1,0,3,1.179696e+13,5.768654e+06,0.354504,1,0,1
53,8,40210,1,1,0,3,5.013273e+10,3.787130e+05,0.349543,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
287910,894,902780,1,1,0,3,3.694655e+12,3.327971e+06,0.333591,1,0,1
287911,894,902810,1,1,0,3,9.682382e+07,1.705300e+04,0.332951,1,0,1
287915,894,902910,1,1,0,3,1.062888e+09,7.286400e+04,0.200199,1,0,1
287916,894,902920,1,1,0,3,4.574197e+09,1.438880e+05,0.220936,1,0,1
287917,894,903032,1,1,0,3,1.545099e+11,6.686900e+05,0.345547,1,0,1
287918,894,903033,1,1,0,3,1.626105e+10,3.154560e+05,0.163407,1,0,1
287919,894,903110,1,1,0,3,7.368144e+09,1.369780e+05,0.392696,1,0,1
287924,894,903290,1,1,0,3,2.650146e+11,1.012169e+06,0.258681,1,0,1
287925,894,903300,1,1,0,3,7.210925e+11,1.400735e+06,0.367518,1,0,1
287926,894,910111,1,1,0,3,2.157954e+08,2.509100e+04,0.342773,1,0,1
287941,894,920510,1,1,0,3,1.700730e+07,6.763000e+03,0.371840,1,0,1
287942,894,920890,1,1,0,3,1.834460e+07,7.687000e+03,0.310452,1,0,1
287951,894,940130,1,1,0,3,2.100851e+11,8.342760e+05,0.301839,1,0,1
287955,894,940290,1,1,0,3,2.403317e+12,3.238138e+06,0.229203,1,0,1
287959,894,940520,1,1,0,3,2.024866e+10,2.575370e+05,0.305293,1,0,1
287962,894,940591,1,1,0,3,8.997949e+08,5.157000e+04,0.338337,1,0,1
287967,894,950662,1,1,0,3,1.540141e+10,2.312410e+05,0.288025,1,0,1
287968,894,950669,1,1,0,3,2.514709e+09,9.361700e+04,0.286932,1,0,1
287974,894,960190,1,1,0,3,1.583152e+08,2.095200e+04,0.360638,1,0,1
287976,894,960310,1,1,0,3,4.340209e+10,4.302400e+05,0.234471,1,0,1
287977,894,960340,1,1,0,3,9.123737e+10,5.023980e+05,0.361474,1,0,1
287983,894,960711,1,1,0,3,8.039319e+08,4.823200e+04,0.345580,1,0,1
287988,894,960910,1,1,0,3,1.806333e+10,2.698170e+05,0.248119,1,0,1
287989,894,960920,1,1,0,3,4.988872e+08,3.817800e+04,0.342276,1,0,1
287990,894,961000,1,1,0,3,2.452440e+10,2.701610e+05,0.336011,1,0,1
287991,894,961100,1,1,0,3,4.250239e+09,1.098830e+05,0.352008,1,0,1
287992,894,961210,1,1,0,3,3.656621e+10,3.396510e+05,0.316967,1,0,1
287993,894,961220,1,1,0,3,5.131857e+08,4.456800e+04,0.258362,1,0,1
287998,894,961800,1,1,0,3,1.748528e+08,2.246400e+04,0.346496,1,0,1
287999,894,970190,1,1,0,3,2.909122e+10,2.843580e+05,0.359775,1,0,1

In [90]:

joined_result_grouped = (joined_result.groupby(['product_id']))

joined_result_grouped_sum = joined_result_grouped['filter3_result'].agg('sum').reset_index()

# all_data_grouped_square_sum['concentration'] = all_data_grouped_square_sum["value_sqaure"] / (all_data_grouped_square_sum["value"])**2

In [91]:
joined_result_grouped_sum

      product_id  filter3_result
0          10121              28
1          10129              13
2          10130               2
3          10190               4
4          10221              19
5          10229               5
6          10290               3
7          10310               9
8          10410               9
9          10420               5
10         10512               1
11         10599               1
12         10611               1
13         10612               1
14         10613               1
15         10614               5
16         10619              28
17         10620              14
18         10631               2
19         10632              14
20         10639              14
21         10641               8
22         10649              12
23         10690              21
24         20110               1
25         20120              15
26         20130              27
27         20210               7
28         20220              19
29         20230              33
...          ...             ...
4927      960891              30
4928      960899              47
4929      960910              38
4930      960920              30
4931      960990              40
4932      961000              25
4933      961100              55
4934      961210              81
4935      961220              52
4936      961310              29
4937      961320              13
4938      961380              19
4939      961390              21
4940      961400              18
4941      961511              16
4942      961519              15
4943      961590              19
4944      961610              23
4945      961620              16
4946      961700              10
4947      961800              39
4948      961900              42
4949      970110              28
4950      970190              30
4951      970200              21
4952      970300              18
4953      970400              14
4954      970500              29
4955      970600              19
4956      999999              28

[4957 rows x 2 columns]

In [92]:
joined_result_grouped_sum['filter3_result'].describe()

count    4957.000000
mean       25.804922
std        16.560077
min         1.000000
25%        13.000000
50%        25.000000
75%        38.000000
max        89.000000
Name: filter3_result, dtype: float64

In [93]:
joined_result_grouped_sum.to_csv('Country-No. Recommendation.csv')

In [94]:
ranking = pd.read_csv('../mexico/HH/ranking.csv')

In [95]:
ranking

        country_id  product_id  country_idz  ranking
0              484       10110          124        2
1              484       10110          152        6
2              484       10110          156        7
3              484       10110          170       13
4              484       10110          188       27
5              484       10110          214       30
6              484       10110          218       25
7              484       10110          222       32
8              484       10110          251       19
9              484       10110          276       22
10             484       10110           32       15
11             484       10110          320        9
12             484       10110          340       37
13             484       10110          344        4
14             484       10110           36        5
15             484       10110          372       16
16             484       10110          381       26
17             484       10110          392        3
18             484       10110          410       11
19             484       10110          528       36
20             484       10110          554       28
21             484       10110          558       33
22             484       10110           56       21
23             484       10110          591       17
24             484       10110          604        8
25             484       10110          634       29
26             484       10110          643       40
27             484       10110          682       38
28             484       10110          699       34
29             484       10110          702       18
...            ...         ...          ...      ...
143210         484      970500          344        6
143211         484      970500           36       14
143212         484      970500          376       24
143213         484      970500          381       21
143214         484      970500          392        9
143215         484      970500           40       25
143216         484      970500          410       13
143217         484      970500          442       26
143218         484      970500          458       27
143219         484      970500          490       29
143220         484      970500          528        7
143221         484      970500          554       18
143222         484      970500           56       10
143223         484      970500          579       33
143224         484      970500          591       30
143225         484      970500          604       28
143226         484      970500          616       15
143227         484      970500          634       36
143228         484      970500          643       19
143229         484      970500          702       23
143230         484      970500          703       38
143231         484      970500          710       39
143232         484      970500          724       17
143233         484      970500          752       20
143234         484      970500          757        5
143235         484      970500          764       35
143236         484      970500          784       16
143237         484      970500          792       34
143238         484      970500          826        3
143239         484      970500          842        1

[143240 rows x 4 columns]

In [96]:
def find_ranked_country_list (product_id):

    choose1 = ranking.loc[ranking['product_id'] == product_id].loc[ranking['country_idz'] != 0]

    choose1 = choose1.sort_values("ranking", inplace = False) 

    ranked_index_list = choose1.index.tolist()

    output_list = choose1['country_idz'].loc[ranked_index_list].tolist()

    return (output_list)

In [97]:
output = pd.DataFrame()

output['product_id'] = (ranking['product_id'].unique())

output['ranked_list'] = output['product_id'].apply(lambda x: find_ranked_country_list(x))

output

      product_id                                        ranked_list
0          10110  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...
1          10121  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...
2          10129  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...
3          10130  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...
4          10190  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...
5          10210  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...
6          10221  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...
7          10229  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...
8          10231  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...
9          10239  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...
10         10290  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...
11         10612  [842, 156, 124, 276, 392, 410, 251, 56, 757, 7...
12         10613  [842, 156, 124, 276, 392, 410, 251, 56, 757, 7...
13         10614  [842, 156, 124, 276, 392, 410, 251, 56, 757, 7...
14         10619  [842, 156, 124, 276, 392, 410, 251, 56, 757, 7...
15         10620  [842, 156, 344, 392, 222, 704, 276, 410, 124, ...
16         10641  [842, 124, 392, 528, 276, 724, 320, 56, 410, 1...
17         10649  [842, 124, 392, 528, 276, 724, 320, 56, 410, 1...
18         10690  [842, 124, 392, 528, 276, 724, 320, 56, 410, 1...
19         20120  [842, 124, 410, 76, 784, 381, 392, 792, 152, 1...
20         20130  [842, 392, 152, 320, 276, 124, 528, 410, 222, ...
21         20220  [842, 156, 410, 344, 320, 704, 458, 188, 792, ...
22         20230  [156, 842, 344, 392, 320, 862, 643, 704, 410, ...
23         20312  [842, 381, 392, 616, 276, 344, 251, 826, 724, ...
24         20319  [842, 392, 124, 410, 276, 381, 616, 826, 251, ...
25         20322  [156, 842, 643, 170, 152, 344, 214, 320, 340, ...
26         20329  [156, 842, 392, 643, 170, 410, 152, 344, 124, ...
27         20450  [842, 784, 780, 251, 124, 490, 410, 724, 381, ...
28         20500  [56, 392, 757, 251, 643, 156, 381, 842, 246, 3...
29         20610  [842, 392, 410, 251, 604, 344, 381, 724, 276, ...
...          ...                                                ...
3551      960350  [842, 124, 156, 276, 604, 170, 76, 392, 702, 2...
3552      960390  [842, 124, 276, 320, 340, 251, 56, 188, 826, 2...
3553      960610  [842, 558, 214, 124, 156, 699, 704, 222, 276, ...
3554      960622  [842, 558, 170, 156, 218, 214, 704, 276, 124, ...
3555      960630  [842, 156, 381, 344, 410, 792, 392, 591, 276, ...
3556      960711  [170, 558, 320, 76, 842, 214, 218, 604, 156, 7...
3557      960720  [558, 170, 842, 32, 792, 156, 124, 76, 222, 70...
3558      960810  [842, 320, 276, 251, 170, 76, 124, 32, 156, 22...
3559      960820  [842, 124, 170, 251, 276, 320, 218, 826, 152, ...
3560      960840  [842, 76, 276, 792, 124, 251, 156, 392, 170, 1...
3561      960860  [842, 251, 276, 156, 381, 699, 616, 724, 203, ...
3562      960899  [842, 156, 591, 276, 76, 699, 251, 392, 218, 1...
3563      960910  [842, 604, 170, 276, 320, 124, 32, 152, 76, 18...
3564      960920  [842, 792, 170, 604, 276, 360, 156, 124, 152, ...
3565      960990  [842, 124, 276, 156, 251, 320, 591, 826, 222, ...
3566      961000  [842, 124, 276, 826, 251, 528, 320, 56, 170, 1...
3567      961210  [842, 276, 156, 124, 170, 251, 76, 320, 32, 82...
3568      961220  [842, 124, 192, 170, 276, 251, 826, 56, 604, 3...
3569      961310  [842, 124, 170, 276, 320, 32, 392, 858, 36, 15...
3570      961380  [842, 156, 276, 124, 392, 251, 410, 528, 826, ...
3571      961590  [842, 320, 276, 826, 124, 558, 251, 156, 724, ...
3572      961610  [842, 170, 604, 124, 76, 218, 156, 251, 188, 6...
3573      961700  [842, 156, 276, 124, 392, 56, 600, 152, 682, 8...
3574      961800  [842, 156, 276, 124, 251, 56, 381, 724, 826, 5...
3575      961900  [842, 320, 124, 222, 340, 156, 558, 188, 604, ...
3576      970110  [842, 826, 344, 757, 251, 276, 124, 392, 56, 4...
3577      970190  [842, 826, 757, 124, 276, 56, 702, 410, 251, 3...
3578      970200  [842, 826, 757, 276, 251, 124, 392, 56, 344, 3...
3579      970300  [842, 757, 826, 344, 251, 124, 56, 410, 276, 3...
3580      970500  [842, 276, 826, 251, 757, 344, 528, 124, 392, ...

[3581 rows x 2 columns]

In [105]:
output['number'] = output['ranked_list'].apply(lambda x: len(x))

output

      product_id                                        ranked_list  number
0          10110  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...      40
1          10121  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...      40
2          10129  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...      40
3          10130  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...      40
4          10190  [842, 124, 392, 344, 36, 152, 156, 604, 320, 8...      40
5          10210  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...      40
6          10221  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...      40
7          10229  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...      40
8          10231  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...      40
9          10239  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...      40
10         10290  [842, 792, 156, 704, 124, 360, 422, 400, 340, ...      40
11         10612  [842, 156, 124, 276, 392, 410, 251, 56, 757, 7...      40
12         10613  [842, 156, 124, 276, 392, 410, 251, 56, 757, 7...      40
13         10614  [842, 156, 124, 276, 392, 410, 251, 56, 757, 7...      40
14         10619  [842, 156, 124, 276, 392, 410, 251, 56, 757, 7...      40
15         10620  [842, 156, 344, 392, 222, 704, 276, 410, 124, ...      40
16         10641  [842, 124, 392, 528, 276, 724, 320, 56, 410, 1...      40
17         10649  [842, 124, 392, 528, 276, 724, 320, 56, 410, 1...      40
18         10690  [842, 124, 392, 528, 276, 724, 320, 56, 410, 1...      40
19         20120  [842, 124, 410, 76, 784, 381, 392, 792, 152, 1...      40
20         20130  [842, 392, 152, 320, 276, 124, 528, 410, 222, ...      40
21         20220  [842, 156, 410, 344, 320, 704, 458, 188, 792, ...      40
22         20230  [156, 842, 344, 392, 320, 862, 643, 704, 410, ...      40
23         20312  [842, 381, 392, 616, 276, 344, 251, 826, 724, ...      40
24         20319  [842, 392, 124, 410, 276, 381, 616, 826, 251, ...      40
25         20322  [156, 842, 643, 170, 152, 344, 214, 320, 340, ...      40
26         20329  [156, 842, 392, 643, 170, 410, 152, 344, 124, ...      40
27         20450  [842, 784, 780, 251, 124, 490, 410, 724, 381, ...      40
28         20500  [56, 392, 757, 251, 643, 156, 381, 842, 246, 3...      34
29         20610  [842, 392, 410, 251, 604, 344, 381, 724, 276, ...      40
...          ...                                                ...     ...
3551      960350  [842, 124, 156, 276, 604, 170, 76, 392, 702, 2...      40
3552      960390  [842, 124, 276, 320, 340, 251, 56, 188, 826, 2...      40
3553      960610  [842, 558, 214, 124, 156, 699, 704, 222, 276, ...      40
3554      960622  [842, 558, 170, 156, 218, 214, 704, 276, 124, ...      40
3555      960630  [842, 156, 381, 344, 410, 792, 392, 591, 276, ...      40
3556      960711  [170, 558, 320, 76, 842, 214, 218, 604, 156, 7...      40
3557      960720  [558, 170, 842, 32, 792, 156, 124, 76, 222, 70...      40
3558      960810  [842, 320, 276, 251, 170, 76, 124, 32, 156, 22...      40
3559      960820  [842, 124, 170, 251, 276, 320, 218, 826, 152, ...      40
3560      960840  [842, 76, 276, 792, 124, 251, 156, 392, 170, 1...      40
3561      960860  [842, 251, 276, 156, 381, 699, 616, 724, 203, ...      40
3562      960899  [842, 156, 591, 276, 76, 699, 251, 392, 218, 1...      40
3563      960910  [842, 604, 170, 276, 320, 124, 32, 152, 76, 18...      40
3564      960920  [842, 792, 170, 604, 276, 360, 156, 124, 152, ...      40
3565      960990  [842, 124, 276, 156, 251, 320, 591, 826, 222, ...      40
3566      961000  [842, 124, 276, 826, 251, 528, 320, 56, 170, 1...      40
3567      961210  [842, 276, 156, 124, 170, 251, 76, 320, 32, 82...      40
3568      961220  [842, 124, 192, 170, 276, 251, 826, 56, 604, 3...      40
3569      961310  [842, 124, 170, 276, 320, 32, 392, 858, 36, 15...      40
3570      961380  [842, 156, 276, 124, 392, 251, 410, 528, 826, ...      40
3571      961590  [842, 320, 276, 826, 124, 558, 251, 156, 724, ...      40
3572      961610  [842, 170, 604, 124, 76, 218, 156, 251, 188, 6...      40
3573      961700  [842, 156, 276, 124, 392, 56, 600, 152, 682, 8...      40
3574      961800  [842, 156, 276, 124, 251, 56, 381, 724, 826, 5...      40
3575      961900  [842, 320, 124, 222, 340, 156, 558, 188, 604, ...      40
3576      970110  [842, 826, 344, 757, 251, 276, 124, 392, 56, 4...      40
3577      970190  [842, 826, 757, 124, 276, 56, 702, 410, 251, 3...      40
3578      970200  [842, 826, 757, 276, 251, 124, 392, 56, 344, 3...      40
3579      970300  [842, 757, 826, 344, 251, 124, 56, 410, 276, 3...      40
3580      970500  [842, 276, 826, 251, 757, 344, 528, 124, 392, ...      40

[3581 rows x 3 columns]

In [98]:
joined_result.to_csv('result.csv')

In [99]:
output.to_csv('output.csv')

In [100]:
ranking['filter_3'] = 1

ranking

        country_id  product_id  country_idz  ranking  filter_3
0              484       10110          124        2         1
1              484       10110          152        6         1
2              484       10110          156        7         1
3              484       10110          170       13         1
4              484       10110          188       27         1
5              484       10110          214       30         1
6              484       10110          218       25         1
7              484       10110          222       32         1
8              484       10110          251       19         1
9              484       10110          276       22         1
10             484       10110           32       15         1
11             484       10110          320        9         1
12             484       10110          340       37         1
13             484       10110          344        4         1
14             484       10110           36        5         1
15             484       10110          372       16         1
16             484       10110          381       26         1
17             484       10110          392        3         1
18             484       10110          410       11         1
19             484       10110          528       36         1
20             484       10110          554       28         1
21             484       10110          558       33         1
22             484       10110           56       21         1
23             484       10110          591       17         1
24             484       10110          604        8         1
25             484       10110          634       29         1
26             484       10110          643       40         1
27             484       10110          682       38         1
28             484       10110          699       34         1
29             484       10110          702       18         1
...            ...         ...          ...      ...       ...
143210         484      970500          344        6         1
143211         484      970500           36       14         1
143212         484      970500          376       24         1
143213         484      970500          381       21         1
143214         484      970500          392        9         1
143215         484      970500           40       25         1
143216         484      970500          410       13         1
143217         484      970500          442       26         1
143218         484      970500          458       27         1
143219         484      970500          490       29         1
143220         484      970500          528        7         1
143221         484      970500          554       18         1
143222         484      970500           56       10         1
143223         484      970500          579       33         1
143224         484      970500          591       30         1
143225         484      970500          604       28         1
143226         484      970500          616       15         1
143227         484      970500          634       36         1
143228         484      970500          643       19         1
143229         484      970500          702       23         1
143230         484      970500          703       38         1
143231         484      970500          710       39         1
143232         484      970500          724       17         1
143233         484      970500          752       20         1
143234         484      970500          757        5         1
143235         484      970500          764       35         1
143236         484      970500          784       16         1
143237         484      970500          792       34         1
143238         484      970500          826        3         1
143239         484      970500          842        1         1

[143240 rows x 5 columns]

In [101]:

ranking_grouped = (ranking.groupby(['product_id']))

ranking_grouped_sum = ranking_grouped['filter_3'].agg('sum').reset_index()

# all_data_grouped_square_sum['concentration'] = all_data_grouped_square_sum["value_sqaure"] / (all_data_grouped_square_sum["value"])**2

In [102]:
ranking_grouped_sum

      product_id  filter_3
0          10110        40
1          10121        40
2          10129        40
3          10130        40
4          10190        40
5          10210        40
6          10221        40
7          10229        40
8          10231        40
9          10239        40
10         10290        40
11         10612        40
12         10613        40
13         10614        40
14         10619        40
15         10620        40
16         10641        40
17         10649        40
18         10690        40
19         20120        40
20         20130        40
21         20220        40
22         20230        40
23         20312        40
24         20319        40
25         20322        40
26         20329        40
27         20450        40
28         20500        40
29         20610        40
...          ...       ...
3551      960350        40
3552      960390        40
3553      960610        40
3554      960622        40
3555      960630        40
3556      960711        40
3557      960720        40
3558      960810        40
3559      960820        40
3560      960840        40
3561      960860        40
3562      960899        40
3563      960910        40
3564      960920        40
3565      960990        40
3566      961000        40
3567      961210        40
3568      961220        40
3569      961310        40
3570      961380        40
3571      961590        40
3572      961610        40
3573      961700        40
3574      961800        40
3575      961900        40
3576      970110        40
3577      970190        40
3578      970200        40
3579      970300        40
3580      970500        40

[3581 rows x 2 columns]